"""Modified nullable constriants

Revision ID: 8856688f3151
Revises: c27813ba3f33
Create Date: 2024-12-24 09:58:08.139187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8856688f3151'
down_revision = 'c27813ba3f33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('desc',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.alter_column('desc',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('role',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###
